DATA_DIR: /home/benz/bert-ranking/antique_preprocessed
FOLD_NAME: fold_0
accelerator: ddp
accumulate_grad_batches: 1
batch_size: 32
bert_dim: 768
bert_type: bert-base-uncased
data_file: !!python/object/apply:pathlib.PosixPath
- /
- home
- benz
- bert-ranking
- antique_preprocessed
- data.h5
dropout: 0.1
freeze_bert: false
gpus:
- 1
limit_test_batches: 9223372036854775807
limit_train_batches: 9223372036854775807
limit_val_batches: 9223372036854775807
load_weights: null
loss_margin: 0.2
lr: 3.0e-05
max_epochs: 20
num_workers: 16
precision: 32
random_seed: 123
save_dir: out
save_top_k: 1
test: false
test_file: !!python/object/apply:pathlib.PosixPath
- /
- home
- benz
- bert-ranking
- antique_preprocessed
- fold_0
- test.h5
train_file_pairwise: !!python/object/apply:pathlib.PosixPath
- /
- home
- benz
- bert-ranking
- antique_preprocessed
- fold_0
- train_pairwise.h5
train_file_pointwise: !!python/object/apply:pathlib.PosixPath
- /
- home
- benz
- bert-ranking
- antique_preprocessed
- fold_0
- train_pointwise.h5
training_mode: pointwise
val_check_interval: 1.0
val_file: !!python/object/apply:pathlib.PosixPath
- /
- home
- benz
- bert-ranking
- antique_preprocessed
- fold_0
- val.h5
val_patience: 3
warmup_steps: 1000
